language: ruby
rvm:
    - 2.3
    - 2.4
    - 2.5
cache: bundler
sudo: required
before_install:
  - bash test/ci/setup.sh
script:
  - COVERALLS=1 make test
  - make test-cli
after_script:
  - bash test/ci/teardown.sh
notifications:
  irc:
    channels:
      - "chat.freenode.net#kbsecret"
    on_success: change
    on_failure: always
