language: ruby
rvm:
    - 2.3
    - 2.4
    - 2.5
cache: bundler
sudo: required
before_install:
  - gem install bundler # https://github.com/travis-ci/travis-ci/issues/9333#issuecomment-373042916
  - bash test/ci/setup.sh
script:
  - COVERALLS=1 make test
after_script:
  - bash test/ci/teardown.sh
notifications:
  irc:
    channels:
      - "chat.freenode.net#kbsecret"
    on_success: change
    on_failure: always
